version: '3.9'

services:
  mongo:
    image: mongo:5.0.7
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./db_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mangouser
      - MONGO_INITDB_ROOT_PASSWORD=m@ng0

volumes:
  db_data: {}
