#!/bin/bash

CONTAINER_ID=$(docker container list --filter NAME=mongo --format '{{.ID}}')

docker exec -it $CONTAINER_ID /usr/bin/mongosh nbd -u mangouser -p m@ng0 --authenticationDatabase=admin --quiet /opt/lab$1/zapytanie_$2.js

exit 0
